name: Scan IPv4 CIDR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scan:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run IPv4_Scan.py
        run: python IPv4_Scan.py "0.0.0.0/28"

      - name: Read Logs
        id: body
        run: |
          echo "BODY<<EOF" >> $GITHUB_ENV
          cat *_Logs.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Release OUTPUT
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "0.0.0.0"
          body: ${{ env.BODY }}
          files: "*_IPs.txt"
